// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections;


class BasicCounting : Question
{
	
	
	Random rnd = new Random(Guid.NewGuid().GetHashCode());
	int correctAnwser;
	
	
	public BasicCounting()
	{
		generateQuestion();
		base.texture = "Counting Question";
		
	}
	
	
	private void generateQuestion()
	{
		
		correctAnwser = rnd.Next(5, 11);
		base.question = string.Format(@"Angry robot will not let player pass until they identify how many 
		flowers there are blocking their path. Must input a single number.
		");
		base.anwsers = generateAnwsers(correctAnwser);
	}
	
	private List<string> generateAnwsers(int anwser)
	{
		
		List<string> anwsers = new List<string>();
		anwsers.Add(anwser.ToString());
		//generate 3 random numbers between 10 that are not the anwser or in the list of anwsers
		string possibleAnwser;
		while (anwsers.Count < 4)
		{
			possibleAnwser = rnd.Next(1, 11).ToString();
			if (!anwsers.Contains(possibleAnwser))
				anwsers.Add(possibleAnwser);
		}
		
		base.correctAnwser = rnd.Next(0, 4);
		anwsers[0] = anwsers[base.correctAnwser];
		anwsers[base.correctAnwser] = anwser.ToString();
		
		return anwsers;
	}
	
	
	public override string checkAnwser(int anwser)
	{
		string response;
		
		if (anwser == base.correctAnwser)
		{
			base.correct = true;
			response = string.Format("That’s right! there are {0} flowers", base.anwsers[base.correctAnwser]);
		}
		else
		{
			if (int.Parse(base.anwsers[base.correctAnwser]) > int.Parse(base.anwsers[anwser]))
			{
				response = string.Format("I don’t see {0} flowers. I see more flowers than that!", base.anwsers[anwser]);
			}
			else
			{
				response = string.Format("I don’t see {0} flowers! That number is too high. There are less flowers in your path!" , base.anwsers[anwser]);
			}
			
		}
		
		return response;
		
	}
	
	
}